typography_spectrum: 0.75632
color:
  brandColors:
    - '#1b0092'
    - '#fffeff'
    - '#414de7'
    - '#439ffa'
    - '#43d5fd'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: rexinvestigations
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Rex Investigations
purpose: []
