name: rexinvestigations
favicon: null
layout_spectrum: 0.5897564941551536
typography_spectrum: 0.75632
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.577378268353641
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
