name: rexinvestigations
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75632
title: Rex Investigtions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b0092'
    - '#fffeff'
    - '#414de7'
    - '#439ffa'
    - '#43d5fd'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
